### ISSUE TITLE
use updated URL for wkhtmltopdf downloads

### ISSUE THREAD

**Issue by ashkulz** [lino-framework/lino#26]
Hello,

wkhtmltopdf has [moved the downloads provider](https://groups.google.com/d/msg/wkhtmltopdf-general/wZwTUol3mXI/GNVeyrKDdqIJ) from SourceForge to gna.org. As mentioned in the linked message, all earlier downloads have been removed from SourceForge and you are strongly advised to migrate to the new URLs. The following files in your repository will need to be updated:
- docs/admin/printable.rst

It is recommended to either subscribe to the [mailing list](https://groups.google.com/forum/#!forum/wkhtmltopdf-general) or [Twitter feed](https://twitter.com/wkhtmltopdf) to receive updates on new releases and further changes.

Thanks,
wkhtmltopdf maintainer

**Comment by lsaffre** [comment]
Thanks for pointing it out. I removed it from that page because afaics that was the wrong place. wkhtmltoimage might be useful  for making screenshots that can be used for tested documentation. First question: can wkhtmltoimage render a Linop page? 

$ wkhtmltoimage http://welfare-demo.lino-framework.org test.png
Loading page (1/2)
Rendering (2/2)                                                    
Error: Will not output an empty image                             
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::translate: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setBrush: Painter not active
QPainter::pen: Painter not active
QPainter::setPen: Painter not active
QPainter::end: Painter not active, aborted
Error: Could not save image
Done                                                               
Exit with code 1, due to unknown error.

So it seems that no. But wkhtmltopdf renders the page partly (only the main menu). We should find out what's the problem there. I need to post this to wkhtmltopdf.

**Comment by ashkulz** [comment]
Looks like you need to use a high `--javascript-delay` and/or `--window-status` to ensure that the page has rendered completely.
